export const TASKS = [
  {
    id: 1,
    title: "Estudar FSC",
    description: "Estudar boas práticas",
    time: "morning",
    status: "done",
  },
  {
    id: 2,
    title: "Ler livro",
    description: "Estudar boas práticas",
    time: "morning",
    status: "done",
  },
  {
    id: 3,
    title: "Treinar",
    description: "Treinar na Academia",
    time: "afternoon",
    status: "done",
  },
  {
    id: 4,
    title: "Fazer compras",
    description: "Comprar os ingredientes do janta",
    time: "afternoon",
    status: "in_progress",
  },
  {
    id: 5,
    title: "Descancar",
    description: "Comprar os ingredientes do janta",
    time: "evening",
    status: "not_started",
  },
  {
    id: 6,
    title: "Revisar código",
    description: "Revisar pull requests do projeto",
    time: "morning",
    status: "not_started",
  },
  {
    id: 7,
    title: "Responder e-mails",
    description: "Responder mensagens importantes",
    time: "morning",
    status: "in_progress",
  },
  {
    id: 8,
    title: "Almoçar",
    description: "Fazer pausa para o almoço",
    time: "afternoon",
    status: "not_started",
  },
  {
    id: 9,
    title: "Reunião de equipe",
    description: "Participar da reunião diária",
    time: "afternoon",
    status: "in_progress",
  },
  {
    id: 10,
    title: "Assistir série",
    description: "Relaxar assistindo um episódio",
    time: "evening",
    status: "not_started",
  },
  {
    id: 11,
    title: "Planejar o dia seguinte",
    description: "Organizar tarefas para amanhã",
    time: "evening",
    status: "done",
  },
]
